/**
 * Navigation seam: SUMMARY.md → VitePress sidebar links.
 *
 * Invariants (must match `.vitepress/config.ts` with `cleanUrls: false`):
 * - Root `README.md` is synced to `index.md` and served at `/`.
 * - Section `README.md` pages are served at `/path/README.html`; link as `/path/README`.
 * - Other `.md` files link as `/path/to/page` (no `.html` suffix in sidebar).
 */

/** Markdown path from SUMMARY → VitePress sidebar link */
export function mdPathToVitePressLink(filePath) {
  const normalized = filePath.replace(/\\/g, "/").trim();
  if (!/\.md$/i.test(normalized)) {
    return "/" + normalized.replace(/^\//, "").replace(/\/$/, "");
  }
  const base = normalized.slice(0, -3);
  const segments = base.split("/");
  const last = segments[segments.length - 1] || "";
  if (/^readme$/i.test(last)) {
    const dir = segments.slice(0, -1).join("/");
    if (!dir) return "/";
    return "/" + dir + "/README";
  }
  return "/" + base;
}

function indentLevel(line) {
  const m = line.match(/^(\s*)-/);
  if (!m) return null;
  return Math.floor(m[1].length / 2);
}

function parseListItem(line) {
  const trimmed = line.trim();
  const m = trimmed.match(/^-\s*\[([^\]]*)\]\(([^)]+)\)\s*$/);
  if (!m) return null;
  return { text: m[1].trim(), file: m[2].trim() };
}

/** Parse SUMMARY markdown into VitePress sidebar groups */
export function parseSummaryToSidebarGroups(raw, options = {}) {
  const { collapse = true } = options;
  const lines = raw.split(/\r?\n/);

  /** @type {{ text: string, items: any[] }[]} */
  const groups = [];
  let currentGroup = { text: "Start", items: [] };
  groups.push(currentGroup);

  /** @type {{ item: any, level: number }[]} */
  const stack = [];

  for (const line of lines) {
    if (/^##\s+/.test(line)) {
      currentGroup = { text: line.replace(/^##\s+/, "").trim(), items: [] };
      groups.push(currentGroup);
      stack.length = 0;
      continue;
    }

    const level = indentLevel(line);
    if (level === null) continue;

    const parsed = parseListItem(line);
    if (!parsed) continue;

    const node = { text: parsed.text, link: mdPathToVitePressLink(parsed.file) };

    while (stack.length > 0 && stack[stack.length - 1].level >= level) {
      stack.pop();
    }

    if (stack.length === 0) {
      currentGroup.items.push(node);
      stack.push({ item: node, level });
    } else {
      const parent = stack[stack.length - 1].item;
      if (!parent.items) parent.items = [];
      parent.items.push(node);
      stack.push({ item: node, level });
    }
  }

  const seen = new Set();
  function dedupe(items) {
    if (!items) return [];
    const out = [];
    for (const it of items) {
      if (it.items) {
        it.items = dedupe(it.items);
        out.push(it);
        continue;
      }
      if (it.link && seen.has(it.link)) continue;
      if (it.link) seen.add(it.link);
      out.push(it);
    }
    return out;
  }

  for (const g of groups) {
    g.items = dedupe(g.items);
  }

  return finalizeSidebarGroups(groups, { collapse });
}

/**
 * Mark sidebar groups as collapsible (`collapsed: true` → closed by default,
 * toggle in UI; active route's ancestors auto-expand).
 * @param {any[]} items
 */
export function applySidebarCollapse(items) {
  if (!items?.length) return items;
  for (const item of items) {
    if (item.items?.length) {
      item.collapsed = true;
      applySidebarCollapse(item.items);
    }
  }
  return items;
}

/** @param {any[]} groups @param {{ collapse?: boolean }} [options] */
export function finalizeSidebarGroups(groups, { collapse = true } = {}) {
  const filtered = groups.filter((g) => g.items.length > 0);
  if (!collapse) return filtered;
  for (const group of filtered) {
    group.collapsed = true;
    applySidebarCollapse(group.items);
  }
  return filtered;
}

/** All `.md` paths linked from SUMMARY markdown */
export function parseSummaryMarkdownPaths(raw) {
  const paths = new Set();
  const re = /\]\(([^)]+\.md)\)/gi;
  let m;
  while ((m = re.exec(raw)) !== null) {
    paths.add(m[1].replace(/\\/g, "/").trim());
  }
  return paths;
}

/** Map SUMMARY `.md` path → nearest `##` section title */
export function parseSummaryNavContext(raw) {
  const lines = raw.split(/\r?\n/);
  let section = "Overview";
  /** @type {Map<string, string>} */
  const fileToSection = new Map();
  for (const line of lines) {
    if (/^##\s+/.test(line)) {
      section = line.replace(/^##\s+/, "").trim();
      continue;
    }
    const match = line.match(/\]\(([^)]+\.md)\)/i);
    if (match) {
      fileToSection.set(match[1].replace(/\\/g, "/").trim(), section);
    }
  }
  return fileToSection;
}

const SIDEBAR_BANNER =
  "// AUTO-GENERATED by scripts/summary-to-vitepress-sidebar.mjs — do not edit\n";

/** Serialize sidebar groups to committed `.mjs` module contents */
export function formatSidebarModule(groups) {
  return `${SIDEBAR_BANNER}export default ${JSON.stringify(groups, null, 2)}\n`;
}
